FROM eclipse-temurin:17-jdk-alpine AS build

WORKDIR /build

COPY pom.xml mvnw ./
COPY .mvn .mvn
COPY ./ ./

RUN --mount=type=cache,target=/root/.m2,sharing=locked \
    ./mvnw -B -nsu dependency:go-offline && \
    ./mvnw clean package


FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY --from=build /build/nfVault/target/*.jar ./

COPY ./entrypoint.sh ./
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]

EXPOSE 8080 8080